# Солнечная система -- только Солнце и Земля
- type: Star
  R: 30
  color: red
  m: 1.98892e+30
  x: 0
  y: 0
  v_x: 0
  v_y: 0
- type: Planet # Земля
  R: 5
  color: green
  m: 5.974e+24
  x: 1.496e+11
  y: 0
  v_x: 0
  v_y: 1.6e+4

