# Солнечная система
- type: Star
  R: 10
  color: red
  m: 1.98892e+30
  x: 0
  y: 0
  v_x: 0
  v_y: 0
- type: Planet # Меркурий
  R: 2
  color: orange
  m: 3.302e+23
  x: 5.7909e+10
  y: 0
  v_x: 0
  v_y: 4.787e+4
- type: Planet # Венера
  R: 5
  color: blue
  m: 4.869e+24
  x: 1.0821e+11
  y: 0
  v_x: 0
  v_y: 3.502e+4
- type: Planet # Земля
  R: 5
  color: green
  m: 5.974e+24
  x: 1.496e+11
  y: 0
  v_x: 0
  v_y: 2.976e+4
- type: Planet # Марс
  R: 3
  color: red
  m: 6.419e+23
  x: 2.2794e+11
  y: 0
  v_x: 0
  v_y: 2.413e+4
- type: Planet # Юпитер
  R: 20
  color: yellow
  m: 1.899e+27
  x: 7.7841e+11
  y: 0
  v_x: 0
  v_y: 1.307e+4
- type: Planet # Сатурн
  R: 15
  color: white
  m: 5.685e+26
  x: 1.4294e+12
  y: 0
  v_x: 0
  v_y: 9.67e+3
- type: Planet # Уран
  R: 8
  color: gray
  m: 8.685e+25
  x: 2.871e+12
  y: 0
  v_x: 0
  v_y: 6.84e+3
- type: Planet # Нептун
  R: 7
  color: blue
  m: 1.024e+26
  x: 4.4983e+12
  y: 0
  v_x: 0
  v_y: 5.48e+3

